blank_issues_enabled: false
contact_links:
  - name: Syntax highlighting bug report
    url: https://github.com/sublimehq/Packages/issues/new/choose
    about: Create a bug report over at the Packages repository, if you are facing syntax highlighting issues with any of the syntax packages that are shipped by default with Sublime Text.